Repository globe-and-citizen/cnc-portal, pull requests merged in 2024-06, with the labels that each got.

#129 feat: create bank smart contract
  contract/contracts/Bank.sol
  contract/ignition/modules/BankProxyModule.ts
  contract/test/Bank.spec.ts
Labels: enhancement

#160 feat: add pauseable in bank smart contract
  contract/contracts/Bank.sol
  contract/test/Bank.spec.ts
Labels: enhancement

#161 feat: deploy bank smart contract to sepolia
  contract/ignition/deployments/chain-11155111/artifacts/BankModule#Bank.dbg.json
  contract/ignition/deployments/chain-11155111/artifacts/BankModule#Bank.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#Bank.dbg.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#Bank.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#ProxyAdmin.dbg.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#ProxyAdmin.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#TransparentUpgradeableProxy.dbg.json
  contract/ignition/deployments/chain-11155111/artifacts/BankProxyModule#TransparentUpgradeableProxy.json
  contract/ignition/deployments/chain-11155111/build-info/0d2fcd4e30f3a08893f10423f9e1960f.json
  contract/ignition/deployments/chain-11155111/build-info/2670731adaf4d38011e4dddc83f96637.json
  contract/ignition/deployments/chain-11155111/deployed_addresses.json
  contract/ignition/deployments/chain-11155111/journal.jsonl
  contract/ignition/modules/BankProxyModule.ts
Labels: documentation

#131 feature: team's bank account view
  app/src/adapters/web3LibraryAdapter.ts
  app/src/apis/teamApi.ts
  app/src/apis/userApi.ts
  app/src/artifacts/abi/bank.json
  app/src/artifacts/abi/tips.json
  app/src/components/TipsAction.vue
  app/src/components/__tests__/TeamCard.spec.ts
  app/src/components/__tests__/TipsAction.spec.ts
  app/src/components/modals/CreateBankModal.vue
  app/src/components/modals/DepositBankModal.vue
  app/src/components/modals/TransferFromBankModal.vue
  app/src/components/modals/__tests__/CreateBankModal.spec.ts
  app/src/components/modals/__tests__/DepositBankModal.spec.ts
  app/src/composables/bank.ts
  app/src/composables/tips.ts
  app/src/constant/index.ts
  app/src/services/bankService.ts
  app/src/services/tipsService.ts
  app/src/types/interfaces/contract-read-function.interface.ts
  app/src/types/interfaces/contract-transaction-function.interface.ts
  app/src/types/interfaces/index.ts
  app/src/types/team.ts
  app/src/views/SingleTeamView.vue
  app/src/views/TransactionsView.vue
Labels: enhancement

#190 fix: bank action position
  app/src/views/SingleTeamView.vue
Labels: bug

#191 fix: rename tips action button and hide Send tip
  app/src/components/TipsAction.vue
Labels: enhancement

#189 Feat/improve status ux
  app/src/App.vue
  app/src/apis/teamApi.ts
  app/src/apis/userApi.ts
  app/src/components/AddMemberCard.vue
  app/src/components/AddTeamCard.vue
  app/src/components/MemberCard.vue
  app/src/components/__tests__/MemberCard.spec.ts
  app/src/components/modals/AddMemberModal.vue
  app/src/components/modals/AddTeamModal.vue
  app/src/components/modals/DeleteConfirmModal.vue
  app/src/components/modals/EditUserModal.vue
  app/src/components/modals/__tests__/AddMemberModal.spec.ts
  app/src/components/modals/__tests__/AddTeamModal.spec.ts
  app/src/components/modals/__tests__/DeleteConfirmationModal.spec.ts
  app/src/components/modals/__tests__/EditUserModal.spec.ts
  app/src/composables/useCustomFetch.ts
  app/src/composables/useSiwe.ts
  app/src/services/bankService.ts
  app/src/types/member.ts
  app/src/types/team.ts
  app/src/views/SingleTeamView.vue
  app/src/views/TeamView.vue
  app/src/views/__tests__/TeamView.spec.ts
  backend/src/controllers/teamController.ts
  backend/src/controllers/userController.ts
  backend/src/routes/userRoutes.ts
Labels: enhancement, refactor

#195 Feature/modal component
  app/src/App.vue
  app/src/components/ModalComponent.vue
  app/src/components/TheDrawer.vue
  app/src/components/__tests__/TheDrawer.spec.ts
  app/src/components/modals/EditUserForm.vue
  app/src/components/modals/EditUserModal.vue
  app/src/components/modals/__tests__/EditUserModal.spec.ts
Labels: enhancement

#201 feature: create bank proxy deployment on frontend side
  README.md
  app/src/adapters/web3LibraryAdapter.ts
  app/src/artifacts/abi/proxy.json
  app/src/artifacts/bytecode/proxy.ts
  app/src/constant/index.ts
  app/src/services/bankService.ts
Labels: enhancement

#217 feature: create tab navigation in single team view
  app/src/components/TabNavigation.vue
  app/src/components/__tests__/TabNavigation.spec.ts
  app/src/types/index.ts
  app/src/types/single-team-tabs-type.ts
  app/src/views/SingleTeamView.vue
Labels: enhancement
