Repository globe-and-citizen/cnc-portal, pull requests merged in 2024-05, with the labels that each got.

#66 feat: create loading state in Transaction Page
  app/src/components/NavBar.vue
  app/src/components/SkeletonLoading.vue
  app/src/router/index.ts
  app/src/stores/tips.ts
  app/src/views/TransactionsView.vue
Labels: enhancement

#99 feature: add vueuse
  app/package-lock.json
  app/package.json
  app/src/services/authService.ts
  app/src/stores/address.ts
  app/src/stores/user.ts
Labels: enhancement

#110 fix: metamask popup without doing any action
  app/src/App.vue
  app/src/components/NavBar.vue
  app/tsconfig.app.json
Labels: bug

#111 refactor: move logics into view from component and use event on navbar
  app/src/App.vue
  app/src/adapters/web3LibraryAdapter.ts
  app/src/components/NavBar.vue
  app/src/composables/tips.ts
  app/src/services/tipsService.ts
Labels: refactor

#114 Fix/error when trying to login
  app/src/composables/useSiwe.ts
  app/src/utils/errorUtil.ts
  app/src/utils/index.ts
Labels: bug

#130 feature: add bank address to team
  backend/prisma/migrations/20240526062308_add_bank_address_to_team/migration.sql
  backend/prisma/schema.prisma
  backend/src/controllers/teamController.ts
  backend/src/utils/backend_specs.html
  backend/src/utils/backend_specs.yaml
Labels: enhancement

#135 feature: add bank address to team
  backend/prisma/migrations/20240526062308_add_bank_address_to_team/migration.sql
  backend/prisma/schema.prisma
  backend/src/controllers/teamController.ts
  backend/src/utils/backend_specs.html
  backend/src/utils/backend_specs.yaml
Labels: enhancement

#128 fix: smart contract testing and type error
  contract/test/Tips.spec.ts
  contract/test/TipsProxyt.spec.ts
Labels: bug

#104 fix/ logout on token fetch failure
  app/src/apis/__tests__/memberApi.spec.ts
  app/src/apis/authApi.ts
  app/src/apis/memberApi.ts
  app/src/apis/teamApi.ts
  app/src/router/index.ts
Labels: bug

#100 feat/ implement toggling between themes using vueuse
  app/index.html
  app/src/App.vue
  app/src/assets/main.css
  app/src/components/AddMemberCard.vue
  app/src/components/AddTeamCard.vue
  app/src/components/NavBar.vue
  app/src/components/TeamCard.vue
  app/src/components/TheDrawer.vue
  app/src/components/TipsAction.vue
  app/src/components/__tests__/TheDrawer.spec.ts
  app/src/views/SingleTeamView.vue
  app/src/views/TransactionsView.vue
  app/tailwind.config.js
Labels: enhancement
