Repository globe-and-citizen/cnc-portal, pull requests merged in 2025-05, with the labels that each got.

#822 Fix/handle rate limit on coingecko
  app/package-lock.json
  app/package.json
  app/src/components/GenericTokenHoldingsSection.vue
  app/src/components/__tests__/GenericTokenHoldingsSection.spec.ts
  app/src/components/forms/DepositBankForm.vue
  app/src/components/forms/TransferForm.vue
  app/src/components/sections/BankView/BankBalanceSection.vue
  app/src/components/sections/BankView/__tests__/BankBalanceSection.spec.ts
  app/src/components/sections/ExpenseAccountView/ExpenseAccountTotalApproved.vue
  app/src/components/sections/ExpenseAccountView/ExpenseMonthSpent.vue
  app/src/composables/__tests__/useContractBalance.spec.ts
  app/src/composables/useContractBalance.ts
  app/src/main.ts
  app/src/stores/currencyStore.ts
  app/src/views/team/[id]/__tests__/BankView.spec.ts
Labels: bug

#823 feat/update expense UI form
  app/src/components/forms/ApproveExpenseSummaryForm.vue
  app/src/components/forms/ApproveUsersEIP712Form.vue
  app/src/components/forms/__tests__/ApproveExpenseSummaryForm.spec.ts
  app/src/components/forms/__tests__/ApproveUsersEIP712Form.spec.ts
  app/src/components/sections/ExpenseAccountView/ApprovedExpensesSection.vue
  app/src/components/utils/SelectMemberWithTokenInput.vue
  app/src/components/utils/__tests/SelectMemberWithTokenInput.spec.ts
  backend/src/controllers/expenseController.ts
Labels: enhancement

#877 perf: being able to run all CI when label run is added to the PR
  .github/workflows/app-vitest.yml
  .github/workflows/backend-vitest.yml
  .github/workflows/contract-vitest.yml
Labels: run

#866 Feature/create test
  app/README.md
  backend/src/controllers/__tests__/authController.test.ts
  backend/src/controllers/__tests__/userController.test.ts
  backend/src/controllers/authController.ts
  backend/src/controllers/userController.ts
  package-lock.json
Labels: run

#880 Feature/add-clain_work
  app/src/components/sections/CashRemunerationView/CashRemunerationTable.vue
  app/src/components/sections/CashRemunerationView/SubmitClaims.vue
  app/src/components/sections/CashRemunerationView/__tests__/SubmitClaims.spec.ts
  backend/prisma/migrations/20250516085145_add_description_to_claim/migration.sql
  backend/prisma/migrations/20250521102722_add_memo_to_claim/migration.sql
  backend/prisma/schema.prisma
  backend/src/controllers/__tests__/claimController.test.ts
  backend/src/controllers/claimController.ts
Labels: run
